### PR TITLE
Resolved the issue regarding themes not updating

### PR DESCRIPTION
**Pull request by shubhamnanche**
The function to change theme has been moved to the positive ("OK") button of the alert dialog box. The themes are set according to the radio button that has been selected and the state is preserved even after closing and reopening the app.

### CODE REVIEW

**Review by WirelessAlien — CHANGES_REQUESTED** [review]
Its working 👍 but the MainActivity is creating 2 times if the theme is different from system maybe Themes.loadTheme(this) is not called in launcher activity(SplashScreen) that's why. I tried to added that and it solved that problem, maybe you can confirm that.

**Comment by shubhamnanche** [comment]
How were you able to tell that MainActivity was getting created twice? Is there any plugin/software that tells such things??

**Comment by shubhamnanche** [comment]
Hi, I have fixed the MainActivity getting created twice issue and the themes are also working perfectly fine. Please check at your end.

**Comment by WirelessAlien** [comment]
> How were you able to tell that MainActivity was getting created twice? Is there any plugin/software that tells such things??

No. I built the app (included the code of this pr) from your fork and tested on physical device.

**Comment by WirelessAlien** [comment]
> Hi, I have fixed the MainActivity getting created twice issue and the themes are also working perfectly fine. Please check at your end.

Thank you. I checked. Its merged 🤝

**Pull request merged**
